export const surpriseMePrompts = [
  'A talking cat that runs a coffee shop in the woods',
  'A group of penguins playing basketball on the moon',
  'A wizard riding a skateboard while casting spells',
  'A robot detective solving mysteries in a futuristic city',
  'A sloth astronaut exploring a galaxy made of candy',
  'A time-traveling squirrel with a jetpack',
  'A magical library where books come to life',
  'A giraffe wearing a top hat and monocle, enjoying tea',
  'A superhero banana fighting evil fruits',
  'A ninja owl practicing martial arts at midnight',
  'A friendly dragon delivering mail in a medieval village',
  'A polar bear scientist conducting experiments in Antarctica',
  'A singing mermaid performing underwater concerts',
  'A group of friendly aliens having a picnic on Earth',
  'A wise old tree giving advice to forest animals',
  'A robot chef cooking gourmet meals for robots and humans',
  'A playful dolphin painting colorful artwork underwater',
  'A brave little snail competing in a snail racing championship',
  'A time-traveling pirate sailing the seas of different eras',
  'A detective chameleon changing colors to disguise itself',
  'A mischievous ghost playing pranks in a haunted mansion',
  'A friendly robot helping elderly people in the future',
  'A magical rainbow unicorn spreading happiness',
  'A scientist bee inventing new flavors of honey',
  'A group of animals forming a band and making music',
  'A brave ant leading a team to explore the human world',
  'A detective kangaroo solving mysteries in the Australian outback',
  'A superhero squirrel protecting the forest from danger',
  'A jellyfish artist creating beautiful paintings in the ocean',
  'A friendly robot dog playing fetch with children',
  'A wise old owl teaching young owlets about the world',
  'A time-traveling caterpillar transforming into different creatures',
  'A friendly alien helping humans with advanced technology',
  'A robot gardener growing plants on other planets',
  'A magical snowman with the ability to create snow sculptures',
  'A superhero elephant with incredible strength',
  'A scientist parrot inventing a language translator for animals',
  'A brave little fish exploring the depths of the ocean',
  'A mischievous monkey pulling pranks in the jungle',
  'A robot explorer discovering new planets in outer space',
  'A wise old fox outsmarting other animals in the forest',
  'A friendly alien dolphin communicating with humans',
  'A superhero bat with extraordinary hearing abilities',
  'A scientist penguin conducting experiments in the Antarctic lab',
  'A magical fire-breathing dragon protecting its treasure',
  'A time-traveling hummingbird visiting different historical events',
  'A brave little mouse embarking on adventures in human houses',
];