import FileSaver from 'file-saver';
import { surpriseMePrompts } from '../constant';
import { toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


// to get randomPrompt from surpriseMePrompts arrays

export function getRandomPrompt(prompt) {
  const randomIndex = Math.floor(Math.random() * surpriseMePrompts.length);
  const randomPrompt = surpriseMePrompts[randomIndex];

  if (randomPrompt === prompt) return getRandomPrompt(prompt);

  return randomPrompt;
}
// to download specific photo that matches the id
export async function downloadImage(_id, photo) {
  FileSaver.saveAs(photo, `download-${_id}.jpg`);
}

// to download the latest photo which has been generated by AI
export async function downloadLatestImage(photo) {
  if (photo) {
    FileSaver.saveAs(photo, 'downloaded-image.jpg');
  } else {
    toast.warning('No image to download.');
  }
}